### ISSUE TITLE
Bettas can't seem to pathfind to lay eggs when other bubble nets are nearby but unreachable

### ISSUE THREAD

**Issue by Maltshakes** [ElectricVersion/BettaGenetics#1]
I made a series of three pools, each with their own breeding pair of bettas. I bred them from left to right. The middle pool and right-most pool bettas completely ignore the easily accessible bubble nets and only want the neighbor's net (they just squished their faces into the pool walls trying to will themselves to the other side). I bucketed them and placed them near their respective bubble nets, but they ignore it completely or try to return to the neighbor's bubble net. 

![image](https://github.com/user-attachments/assets/7e0cab89-4b4a-4586-a31d-f67163078fd4)

I'm using version 0.1.2

**Comment by ElectricVersion** [comment]
Should be fixed as female bettas now specifically target the nest made by their mate
