### ISSUE TITLE
Bettas lose pregnancy on relog

### ISSUE THREAD

**Issue by Maltshakes** [ElectricVersion/BettaGenetics#2]
Breed a betta, then exit your SP world before it lays eggs. Your betta will lose the pregnancy on relog. Maybe also does the same on server restarts?

EDIT: Seems the pregnancy loss might be purely visual? One of the ladies laid an egg even when her GUI said she wasn't pregnant

I'm using version 0.1.2

**Comment by ElectricVersion** [comment]
Should be fixed in 0.1.4!
